#!/bin/bash
#
# Install the hiCUDA compiler from the compiled source tree.
#
# The script takes the installation root of the hiCUDA compiler as
# the only parameter.
#

##########################################################################
# Check prerequisites.
##########################################################################

# Linux OS
OS_NAME=`uname -s`
if [ "${OS_NAME}" != "Linux" ]; then
    echo
    echo "*** The OS does not appear to be Linux! Abort."
    echo
    exit 1
fi

# GNU make
MAKE="gmake"
if [ ! `type -p ${MAKE}` ]; then
    MAKE="make"
    if [ ! `type -p ${MAKE}` ]; then
        echo
        echo "*** GNU Make does not exist! Abort."
        echo
        exit 1
    fi
fi

# awk and sed
AWK="awk"
if [[ ! `type -p ${AWK}` ]]; then
    echo
    echo "*** AWK does not exist! Please install it."
    echo
    exit 1
fi
SED="sed"
if [[ ! `type -p ${SED}` ]]; then
    echo
    echo "*** SED does not exist! Please install it."
    echo
    exit 1
fi

# csh or tcsh
if [[ ! `type -p csh` && ! `type -p tcsh` ]]; then
    echo
    echo "*** CSH (or TCSH) does not exist! Abort."
    echo
    exit 1
fi

##########################################################################
# Parse the command line.
##########################################################################

# This script only takes one parameter.
if [[ $# != 1 ]]; then
    echo "$0 <hiGPU compiler installation root>"
    exit 1
fi

# Get the absolute installation root.
HICUDA_ROOT="$1"
if [[ "${HICUDA_ROOT}" != /* ]]; then
    HICUDA_ROOT="`pwd`/${HICUDA_ROOT}"
fi

# Make sure that the installation root directory exists.
if [[ ! -d "${HICUDA_ROOT}" ]]; then
    echo
    echo "*** ${HICUDA_ROOT} does not exist! Abort."
    echo
    exit 1
fi

# Save the current directory path.
CURR_DIR=`pwd`

# Convert the absolute path into its standard form.
cd ${HICUDA_ROOT}
HICUDA_ROOT=`pwd`

# Get the directory that contains this script.
cd ${CURR_DIR}      # $0 might be a relative path
cd `dirname $0`
SCRIPT_DIR=`pwd`

##########################################################################
# Install the hiCUDA compiler.
##########################################################################

export TOOLROOT="${HICUDA_ROOT}"

SRC_DIR="${SCRIPT_DIR}/../src"
cd ${SRC_DIR}

# Invoke the makefile.
${MAKE} SHELL=/bin/bash ${DEBUG_FLAG} install
if [[ $? -ne 0 ]]; then
    exit 1
fi

# Copy various scripts to the <bin> folder.
HICUDA_BIN="${HICUDA_ROOT}/bin"

# rmpath.sh, rmpath.csh
cp ${SCRIPT_DIR}/rmpath.sh ${HICUDA_BIN}
cp ${SCRIPT_DIR}/rmpath.csh ${HICUDA_BIN}

# set-hicuda.sh, set-hicuda.csh
# Insert the compiler's installation root to the scripts.
sed "s;##HICUDA_ROOT_STUB##;${HICUDA_ROOT};g" \
    ${SCRIPT_DIR}/set-hicuda.sh > ${HICUDA_BIN}/set-higpu.sh
sed "s;##HICUDA_ROOT_STUB##;${HICUDA_ROOT};g" \
    ${SCRIPT_DIR}/set-hicuda.csh > ${HICUDA_BIN}/set-higpu.csh

# unset-hicuda.sh, unset-hicuda.csh
cp ${SCRIPT_DIR}/unset-hicuda.sh ${HICUDA_BIN}/unset-higpu.sh
cp ${SCRIPT_DIR}/unset-hicuda.csh ${HICUDA_BIN}/unset-higpu.csh

# hiCUDA compiler driver script
HICUDA_SRC_DIR="${SRC_DIR}/osprey/hicuda"
cp ${HICUDA_SRC_DIR}/hicuda.sh ${HICUDA_BIN}/higpu

# Copy whirl2c.h to the <misc> folder.
HICUDA_MISC="${HICUDA_ROOT}/misc"
if [[ ! -d "${HICUDA_MISC}" ]]; then
    mkdir ${HICUDA_MISC}
fi
cp ${SRC_DIR}/osprey/include/whirl2c.h ${HICUDA_MISC}

# Copy documentation in 'docs/build-docs' to 'docs'.
HICUDA_DOCS="${HICUDA_ROOT}/docs"
if [[ -d "${HICUDA_DOCS}" ]]; then
    rm -rf ${HICUDA_DOCS}
fi
BUILD_DOCS_DIR="${SCRIPT_DIR}/../docs"
cp -r ${BUILD_DOCS_DIR} ${HICUDA_ROOT}
# mv ${HICUDA_ROOT}/build-docs ${HICUDA_DOCS};
# Remove SVN metadata.
find ${HICUDA_DOCS} -type d -name "\.svn" | xargs rm -rf

# Link the README file.
cd ${HICUDA_ROOT}
ln -sf docs/README.TXT README

# Set the permission that all files and directories in the installation
# directory are accessible by everyone.
chmod -R go=u-w ${HICUDA_ROOT}/*

echo
echo "===================================================================="
echo "          Successfully installed the hiGPU compiler at             "
echo "              ${HICUDA_ROOT}"
echo "===================================================================="
echo

exit 0

